on:
  push:
    branches: [ 29b_containerize_option3 ]
  pull_request:
    branches: [ 29b_containerize_option3 ]

jobs:
  generate_job:
    runs-on: ubuntu-latest
    name: Generates a web report from binary traces in the current directory
    steps:
      - name: Generates
        uses: esmf-org/profiler-action@v1.32
        with: 
          report_name: 'test-from-generate-web'
      - name: Store output
        uses: actions/upload-artifact@v2
        with:
          name: report_output
          path: /home/esmf-profiler/traces
        