on:
  push:
    branches: [ 29b_containerize_option3 ]
  pull_request:
    branches: [ 29b_containerize_option3 ]

jobs:
  generate_job:
    runs-on: ubuntu-latest
    name: Generates a web report from binary traces in the current directory
    steps:
      - name: Generate report
        uses: esmf-org/profiler-action@v1.36
        with: 
          report_name: 'test-from-generate-web'
      - name: Debug
        run: "pwd && ls -lah /"
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.1.3
        with:
          # Artifact name
          name: web-report
          # A file, directory or wildcard pattern that describes what to upload
          path: ./data