on:
  push:
    branches: [ 29b_containerize_option3 ]
  pull_request:
    branches: [ 29b_containerize_option3 ]

jobs:
  generate_job:
    runs-on: ubuntu-latest
    name: Generates a web report from binary traces in the current directory
    steps:
      - name: Generate report
        uses: esmf-org/profiler-action@v1.33
        with: 
          report_name: 'test-from-generate-web'
  
      - name: Store output
        uses: actions/download-artifact@v2
        with:
          name: report_output
          path: ${{ github.workspace }}/traces/**/*
          if-no-files-found: error
          retention-days: 7
        